// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nnjlycbxplqngrcaulhk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5uamx5Y2J4cGxxbmdyY2F1bGhrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwNzk5OTEsImV4cCI6MjA2NzY1NTk5MX0.raz-u9cdnTw-HMZ5CjEDZh-cj1lAt6kxmMgkrTZVyUE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});